name: excell_creater
description: Excell Create

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  hooks_riverpod: ^2.0.0-dev.9
  flutter_hooks: ^0.18.5+1
  path_provider: ^2.0.11
  objectbox: ^1.6.0
  objectbox_flutter_libs: ^1.6.0
  shared_preferences: ^2.0.15
  file_picker: ^4.6.1
  currency_text_input_formatter: ^2.1.7
  flex_color_scheme: ^5.0.1
  path: ^1.8.1
  collection: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.1.11
  objectbox_generator: ^1.6.0

flutter:
  uses-material-design: true
